import { beforeEach, describe, expect, it, vi } from "vitest";
import { blankTitleQuest, choiceTask, duplicateOptionIdsQuest, foreignCorrectOptionQuest, malformedSingleChoiceQuest, malformedTextQuest, missingCorrectOptionQuest, overlongDescriptionQuest, publicationRpcRowFixtures, questId, textTask, tooManyTasksQuest, unsupportedTaskQuest, validMixedQuest, validQuest, warningsOnlyQuest, zeroTaskQuest } from "@/tests/fixtures/teacher-publication";
const m=vi.hoisted(()=>({createClient:vi.fn(),auth:vi.fn(),from:vi.fn(),rpc:vi.fn()}));
vi.mock("server-only",()=>({})); vi.mock("@/lib/supabase/server",()=>({createClient:m.createClient}));
import { getOwnedQuestPublicationReadiness, setOwnedQuestPublicationState } from "@/services/teacher-publication.server";
function client(quest:unknown,tasks:unknown,error=false){let n=0;const q={select:vi.fn().mockReturnThis(),eq:vi.fn().mockReturnThis(),maybeSingle:vi.fn(async()=>n++?{data:tasks,error:error?{}:null}:{data:quest,error:error?{}:null}),order:vi.fn()};q.order.mockReturnValueOnce(q).mockResolvedValueOnce({data:tasks,error:null});m.auth.mockResolvedValue({data:{user:{id:"owner"}}});m.from.mockReturnValue(q);m.createClient.mockResolvedValue({auth:{getUser:m.auth},from:m.from});}
function publicationClient(data: unknown, error: unknown = null, user: unknown = { id: "owner" }) {
  m.auth.mockResolvedValue({ data: { user } });
  m.rpc.mockResolvedValue({ data, error });
  m.createClient.mockResolvedValue({ auth: { getUser: m.auth }, rpc: m.rpc });
}

describe("publication action", () => {
  beforeEach(() => vi.clearAllMocks());
  it("returns unauthorized without calling the publication RPC", async () => {
    publicationClient([], null, null);
    await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "unauthorized" });
    expect(m.rpc).not.toHaveBeenCalled(); expect(m.from).not.toHaveBeenCalled();
  });
  it("returns not_found for a malformed UUID without calling the publication RPC", async () => {
    await expect(setOwnedQuestPublicationState("not-a-uuid", "publish")).resolves.toEqual({ status: "not_found" });
    expect(m.createClient).not.toHaveBeenCalled(); expect(m.rpc).not.toHaveBeenCalled();
  });
  it("maps published and sends a publish RPC request", async () => {
    publicationClient([{ ...publicationRpcRowFixtures.published }]);
    await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "ok", publication: { isPublic: true, outcome: "published" } });
    expect(m.rpc).toHaveBeenCalledTimes(1); expect(m.rpc).toHaveBeenCalledWith("set_owned_quest_publication_state", { p_quest_id: questId, p_publish: true }); expect(m.from).not.toHaveBeenCalled();
  });
  it("maps already_published", async () => {
    publicationClient([{ ...publicationRpcRowFixtures.alreadyPublished }]);
    await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "ok", publication: { isPublic: true, outcome: "already_published" } });
  });
  it("maps unpublished and sends an unpublish RPC request", async () => {
    publicationClient([{ ...publicationRpcRowFixtures.unpublished }]);
    await expect(setOwnedQuestPublicationState(questId, "unpublish")).resolves.toEqual({ status: "ok", publication: { isPublic: false, outcome: "unpublished" } });
    expect(m.rpc).toHaveBeenCalledWith("set_owned_quest_publication_state", { p_quest_id: questId, p_publish: false });
  });
  it("maps already_draft", async () => {
    publicationClient([{ ...publicationRpcRowFixtures.alreadyDraft }]);
    await expect(setOwnedQuestPublicationState(questId, "unpublish")).resolves.toEqual({ status: "ok", publication: { isPublic: false, outcome: "already_draft" } });
  });
  it("maps blocked draft publication", async () => {
    publicationClient([{ ...publicationRpcRowFixtures.blockedDraft }]);
    await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "blocked" });
  });
  it("maps blocked already-public publication", async () => {
    publicationClient([{ ...publicationRpcRowFixtures.blockedPublic }]);
    await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "blocked" });
  });
  it("maps RPC not_found owner-safely", async () => {
    publicationClient([{ ...publicationRpcRowFixtures.notFound }]);
    await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "not_found" });
  });
  it("maps an RPC error to a safe error", async () => {
    publicationClient(null, { message: "RAW_DB_MESSAGE_DO_NOT_EXPOSE", details: "RAW_DB_DETAIL_DO_NOT_EXPOSE" });
    const result = await setOwnedQuestPublicationState(questId, "publish"); expect(result).toEqual({ status: "error" }); expect(JSON.stringify(result)).not.toMatch(/RAW_DB_MESSAGE_DO_NOT_EXPOSE|RAW_DB_DETAIL_DO_NOT_EXPOSE/);
  });
  it("maps an empty RPC result to error", async () => { publicationClient([]); await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "error" }); });
  it("maps multiple RPC rows to error", async () => { publicationClient([publicationRpcRowFixtures.published, publicationRpcRowFixtures.alreadyPublished]); await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "error" }); });
  it("maps null RPC data to error", async () => { publicationClient(null); await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "error" }); });
  it("maps non-array RPC data to error", async () => { publicationClient({ is_public: true, outcome: "published" }); await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "error" }); });
  it("maps a malformed RPC row to error", async () => { publicationClient([null]); await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "error" }); });
  it("maps malformed is_public to error", async () => { publicationClient([{ is_public: "true", outcome: "published" }]); await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "error" }); });
  it("maps an unknown outcome to error", async () => { publicationClient([{ is_public: true, outcome: "unexpected" }]); await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "error" }); });
  it("maps inconsistent published state to error", async () => { publicationClient([{ is_public: false, outcome: "published" }]); await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "error" }); });
  it("rejects already_published with is_public false", async () => {
    publicationClient([{ is_public: false, outcome: "already_published" }]);
    const result = await setOwnedQuestPublicationState(questId, "publish");
    expect(result).toEqual({ status: "error" });
    expect(m.rpc).toHaveBeenCalledTimes(1);
    expect(m.rpc).toHaveBeenCalledWith("set_owned_quest_publication_state", { p_quest_id: questId, p_publish: true });
    expect(JSON.stringify(result)).not.toMatch(/RAW_DB_MESSAGE|RAW_DB_DETAIL/);
  });
  it("maps inconsistent unpublished state to error", async () => { publicationClient([{ is_public: true, outcome: "unpublished" }]); await expect(setOwnedQuestPublicationState(questId, "unpublish")).resolves.toEqual({ status: "error" }); });
  it("rejects already_draft with is_public true", async () => {
    publicationClient([{ is_public: true, outcome: "already_draft" }]);
    const result = await setOwnedQuestPublicationState(questId, "unpublish");
    expect(result).toEqual({ status: "error" });
    expect(m.rpc).toHaveBeenCalledTimes(1);
    expect(m.rpc).toHaveBeenCalledWith("set_owned_quest_publication_state", { p_quest_id: questId, p_publish: false });
    expect(JSON.stringify(result)).not.toMatch(/RAW_DB_MESSAGE|RAW_DB_DETAIL/);
  });
  it("maps inconsistent not_found state to error", async () => { publicationClient([{ is_public: true, outcome: "not_found" }]); await expect(setOwnedQuestPublicationState(questId, "publish")).resolves.toEqual({ status: "error" }); });
});
describe("publication readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("returns safe readiness",async()=>{client({...validQuest},[{...textTask},{...choiceTask}]);const r=await getOwnedQuestPublicationReadiness(questId);expect(r.status).toBe("ok");if(r.status==="ok"){expect(r.readiness.ready).toBe(true);expect(JSON.stringify(r.readiness)).not.toMatch(/correctOptionId|content|author_id/);}});it("maps validMixedQuest to an allowlisted ready DTO",async()=>{client({...validMixedQuest.quest},validMixedQuest.tasks.map((task)=>({...task})));const r=await getOwnedQuestPublicationReadiness(questId);expect(r.status).toBe("ok");if(r.status==="ok"){expect(r.readiness.ready).toBe(true);expect(r.readiness.blockers).toEqual([]);expect(r.readiness.taskCount).toBe(validMixedQuest.tasks.length);expect(r.readiness.supportedTaskCount).toBe(validMixedQuest.tasks.length);expect(JSON.stringify(r.readiness)).not.toMatch(/correctOptionId|content|author_id|owner/);}});it("keeps warningsOnlyQuest ready with allowlisted warnings",async()=>{client({...warningsOnlyQuest.quest},warningsOnlyQuest.tasks.map((task)=>({...task})));const r=await getOwnedQuestPublicationReadiness(questId);expect(r.status).toBe("ok");if(r.status==="ok"){expect(r.readiness.ready).toBe(true);expect(r.readiness.blockers).toEqual([]);expect(r.readiness.warnings.length).toBeGreaterThan(0);expect(r.readiness.taskCount).toBe(warningsOnlyQuest.tasks.length);expect(r.readiness.supportedTaskCount).toBe(warningsOnlyQuest.tasks.length);expect(JSON.stringify(r.readiness)).not.toMatch(/correctOptionId|content|author_id|owner/);}});it("blocks malformed cases",async()=>{for(const tasks of [[],Array.from({length:101},()=>({...textTask})),[{...textTask,task_type:"bad"}],[{...choiceTask,content:{options:[{id:"a",text:"A"},{id:"a",text:"B"}],correctOptionId:"a"}}],[{...choiceTask,content:{options:[{id:"a",text:"A"},{id:"b",text:"B"}]}}],[{...choiceTask,content:{options:[{id:"a",text:"A"},{id:"b",text:"B"}],correctOptionId:"x"}}]]){client({...validQuest},tasks);const r=await getOwnedQuestPublicationReadiness(questId);expect(r.status==="ok"&&r.readiness.ready).toBe(false);}});it("returns safe auth/not-found/error outcomes",async()=>{m.auth.mockResolvedValue({data:{user:null}});m.createClient.mockResolvedValue({auth:{getUser:m.auth}});await expect(getOwnedQuestPublicationReadiness(questId)).resolves.toEqual({status:"unauthorized"});client(null,[]);await expect(getOwnedQuestPublicationReadiness(questId)).resolves.toEqual({status:"not_found"});client(validQuest,[],true);await expect(getOwnedQuestPublicationReadiness(questId)).resolves.toEqual({status:"error"});});});
describe("blank title readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("blocks blankTitleQuest with quest_title_blank",async()=>{client({...blankTitleQuest.quest},blankTitleQuest.tasks.map((task)=>({...task})));const r=await getOwnedQuestPublicationReadiness(questId);expect(r.status).toBe("ok");if(r.status==="ok"){expect(r.readiness.ready).toBe(false);expect(r.readiness.blockers.map((x)=>x.code)).toContain("quest_title_blank");expect(r.readiness.taskCount).toBe(blankTitleQuest.tasks.length);expect(r.readiness.supportedTaskCount).toBe(blankTitleQuest.tasks.length);expect(r.readiness.warnings.length).toBeGreaterThanOrEqual(0);expect(JSON.stringify(r.readiness)).not.toMatch(/correctOptionId|content|author_id|owner/);}});});
describe("overlong description readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("blocks overlongDescriptionQuest with quest_description_too_long",async()=>{client({...overlongDescriptionQuest.quest},overlongDescriptionQuest.tasks.map((task)=>({...task})));const r=await getOwnedQuestPublicationReadiness(questId);expect(r.status).toBe("ok");if(r.status==="ok"){const blocker=r.readiness.blockers.find((x)=>x.code==="quest_description_too_long");expect(r.readiness.ready).toBe(false);expect(blocker?.field).toBe("description");expect(r.readiness.taskCount).toBe(overlongDescriptionQuest.tasks.length);expect(r.readiness.supportedTaskCount).toBe(overlongDescriptionQuest.tasks.length);expect(JSON.stringify(r.readiness)).not.toContain(overlongDescriptionQuest.quest.description);expect(JSON.stringify(r.readiness)).not.toMatch(/correctOptionId|content|author_id|owner/);}});});
describe("zero task readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("blocks zeroTaskQuest with task_count_too_low",async()=>{client({...zeroTaskQuest.quest},[]);const result=await getOwnedQuestPublicationReadiness(questId);expect(result.status).toBe("ok");if(result.status!=="ok")throw new Error(`Expected ok result, received ${result.status}`);const readiness=result.readiness;expect(readiness.ready).toBe(false);expect(readiness.taskCount).toBe(0);expect(readiness.supportedTaskCount).toBe(0);expect(readiness.blockers).toContainEqual(expect.objectContaining({code:"task_count_too_low"}));});});
describe("too many tasks readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("blocks tooManyTasksQuest when task count exceeds 100",async()=>{client({...tooManyTasksQuest.quest},tooManyTasksQuest.tasks);const result=await getOwnedQuestPublicationReadiness(questId);expect(result.status).toBe("ok");if(result.status!=="ok")throw new Error(`Expected ok result, received ${result.status}`);const readiness=result.readiness;expect(readiness.ready).toBe(false);expect(readiness.taskCount).toBe(101);expect(readiness.supportedTaskCount).toBe(101);expect(readiness.blockers).toContainEqual(expect.objectContaining({code:"task_count_too_high"}));});});
describe("unsupported task readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("blocks unsupportedTaskQuest with unsupported task type",async()=>{client({...unsupportedTaskQuest.quest},unsupportedTaskQuest.tasks);const result=await getOwnedQuestPublicationReadiness(questId);expect(result.status).toBe("ok");if(result.status!=="ok")throw new Error(`Expected ok result, received ${result.status}`);const readiness=result.readiness;expect(readiness.ready).toBe(false);expect(readiness.taskCount).toBe(unsupportedTaskQuest.tasks.length);expect(readiness.supportedTaskCount).toBeLessThan(readiness.taskCount);expect(readiness.blockers).toContainEqual(expect.objectContaining({code:"unsupported_task_type"}));expect(JSON.stringify(readiness)).not.toMatch(/correctOptionId|content|author_id|owner/);});});
describe("malformed text readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("blocks malformedTextQuest with malformed text task",async()=>{client({...malformedTextQuest.quest},malformedTextQuest.tasks);const result=await getOwnedQuestPublicationReadiness(questId);expect(result.status).toBe("ok");if(result.status!=="ok")throw new Error(`Expected ok result, received ${result.status}`);const readiness=result.readiness;expect(readiness.ready).toBe(false);expect(readiness.taskCount).toBe(malformedTextQuest.tasks.length);expect(readiness.supportedTaskCount).toBe(malformedTextQuest.tasks.length);expect(readiness.blockers).toContainEqual(expect.objectContaining({code:"task_title_blank"}));expect(JSON.stringify(readiness)).not.toMatch(/correctOptionId|content|author_id|owner/);});});
describe("malformed single-choice readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("blocks malformedSingleChoiceQuest with malformed single-choice task",async()=>{client({...malformedSingleChoiceQuest.quest},malformedSingleChoiceQuest.tasks);const result=await getOwnedQuestPublicationReadiness(questId);expect(result.status).toBe("ok");if(result.status!=="ok")throw new Error(`Expected ok result, received ${result.status}`);const readiness=result.readiness;expect(readiness.ready).toBe(false);expect(readiness.taskCount).toBe(malformedSingleChoiceQuest.tasks.length);expect(readiness.supportedTaskCount).toBe(malformedSingleChoiceQuest.tasks.length);expect(readiness.blockers).toContainEqual(expect.objectContaining({code:"invalid_option_count"}));const serialized=JSON.stringify(readiness);expect(serialized).not.toContain(JSON.stringify(malformedSingleChoiceQuest.tasks[0].content));expect(serialized).not.toMatch(/correctOptionId|author_id|owner/);});});
describe("duplicate option ids readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("blocks duplicateOptionIdsQuest with duplicate option ids",async()=>{client({...duplicateOptionIdsQuest.quest},duplicateOptionIdsQuest.tasks);const result=await getOwnedQuestPublicationReadiness(questId);expect(result.status).toBe("ok");if(result.status!=="ok")throw new Error(`Expected ok result, received ${result.status}`);const readiness=result.readiness;expect(readiness.ready).toBe(false);expect(readiness.taskCount).toBe(duplicateOptionIdsQuest.tasks.length);expect(readiness.supportedTaskCount).toBe(duplicateOptionIdsQuest.tasks.length);expect(readiness.blockers).toContainEqual(expect.objectContaining({code:"invalid_options"}));const serialized=JSON.stringify(readiness);expect(serialized).not.toContain(JSON.stringify(duplicateOptionIdsQuest.tasks[0].content));expect(serialized).not.toMatch(/correctOptionId|author_id|owner/);});});
describe("missing correct option readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("blocks missingCorrectOptionQuest when correct option is missing",async()=>{client({...missingCorrectOptionQuest.quest},missingCorrectOptionQuest.tasks);const result=await getOwnedQuestPublicationReadiness(questId);expect(result.status).toBe("ok");if(result.status!=="ok")throw new Error(`Expected ok result, received ${result.status}`);const readiness=result.readiness;expect(readiness.ready).toBe(false);expect(readiness.taskCount).toBe(missingCorrectOptionQuest.tasks.length);expect(readiness.supportedTaskCount).toBe(missingCorrectOptionQuest.tasks.length);expect(readiness.blockers).toContainEqual(expect.objectContaining({code:"invalid_correct_option"}));const serialized=JSON.stringify(readiness);expect(serialized).not.toContain(JSON.stringify(missingCorrectOptionQuest.tasks[0].content));expect(serialized).not.toMatch(/correctOptionId|author_id|owner/);});});
describe("foreign correct option readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("blocks foreignCorrectOptionQuest when correct option is not in options",async()=>{client({...foreignCorrectOptionQuest.quest},foreignCorrectOptionQuest.tasks);const result=await getOwnedQuestPublicationReadiness(questId);expect(result.status).toBe("ok");if(result.status!=="ok")throw new Error(`Expected ok result, received ${result.status}`);const readiness=result.readiness;expect(readiness.ready).toBe(false);expect(readiness.taskCount).toBe(foreignCorrectOptionQuest.tasks.length);expect(readiness.supportedTaskCount).toBe(foreignCorrectOptionQuest.tasks.length);expect(readiness.blockers).toContainEqual(expect.objectContaining({code:"invalid_correct_option"}));const serialized=JSON.stringify(readiness);expect(serialized).not.toContain(JSON.stringify(foreignCorrectOptionQuest.tasks[0].content));expect(serialized).not.toMatch(/correctOptionId|author_id|owner/);});});
describe("unauthenticated readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("returns unauthorized when no authenticated user exists",async()=>{m.auth.mockResolvedValue({data:{user:null}});m.createClient.mockResolvedValue({auth:{getUser:m.auth}});await expect(getOwnedQuestPublicationReadiness(questId)).resolves.toEqual({status:"unauthorized"});expect(m.from).not.toHaveBeenCalled();});});
describe("missing owned quest readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("returns not_found when the owned quest lookup has no row",async()=>{const query={select:vi.fn(),eq:vi.fn(),maybeSingle:vi.fn().mockResolvedValue({data:null,error:null}),order:vi.fn(),insert:vi.fn(),update:vi.fn(),delete:vi.fn(),upsert:vi.fn()};query.select.mockReturnValue(query);query.eq.mockReturnValue(query);m.auth.mockResolvedValue({data:{user:{id:"owner"}}});m.from.mockReturnValue(query);m.createClient.mockResolvedValue({auth:{getUser:m.auth},from:m.from});await expect(getOwnedQuestPublicationReadiness(questId)).resolves.toEqual({status:"not_found"});expect(m.from).toHaveBeenCalledTimes(1);expect(m.from).toHaveBeenCalledWith("quests");expect(query.eq).toHaveBeenNthCalledWith(1,"id",questId);expect(query.eq).toHaveBeenNthCalledWith(2,"author_id","owner");expect(query.order).not.toHaveBeenCalled();expect(query.insert).not.toHaveBeenCalled();expect(query.update).not.toHaveBeenCalled();expect(query.delete).not.toHaveBeenCalled();expect(query.upsert).not.toHaveBeenCalled();});});
describe("Supabase error readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("returns error without exposing raw Supabase details",async()=>{const query={select:vi.fn(),eq:vi.fn(),maybeSingle:vi.fn().mockResolvedValue({data:null,error:{message:"RAW_DB_MESSAGE_DO_NOT_EXPOSE",details:"RAW_DB_DETAIL_DO_NOT_EXPOSE"}}),order:vi.fn(),insert:vi.fn(),update:vi.fn(),delete:vi.fn(),upsert:vi.fn()};query.select.mockReturnValue(query);query.eq.mockReturnValue(query);m.auth.mockResolvedValue({data:{user:{id:"owner"}}});m.from.mockReturnValue(query);m.createClient.mockResolvedValue({auth:{getUser:m.auth},from:m.from});const result=await getOwnedQuestPublicationReadiness(questId);expect(result).toEqual({status:"error"});const serialized=JSON.stringify(result);expect(serialized).not.toContain("RAW_DB_MESSAGE_DO_NOT_EXPOSE");expect(serialized).not.toContain("RAW_DB_DETAIL_DO_NOT_EXPOSE");expect(serialized).not.toMatch(/author_id|owner/);expect(m.from).toHaveBeenCalledTimes(1);expect(m.from).toHaveBeenCalledWith("quests");expect(query.order).not.toHaveBeenCalled();expect(query.insert).not.toHaveBeenCalled();expect(query.update).not.toHaveBeenCalled();expect(query.delete).not.toHaveBeenCalled();expect(query.upsert).not.toHaveBeenCalled();});});

describe("multiple-choice readiness",()=>{beforeEach(()=>vi.clearAllMocks());it("accepts valid Multiple Choice and blocks incomplete or duplicate-normalized content",async()=>{const valid={...choiceTask,task_type:"multiple_choice",content:{options:[{id:"a",text:"Тараз"},{id:"b",text:"Москва"}],correctOptionIds:["a","b"]}};client({...validQuest},[valid]);let result=await getOwnedQuestPublicationReadiness(questId);expect(result.status==="ok"&&result.readiness.ready).toBe(true);for(const content of [null,{options:[{id:"a",text:"Тараз"},{id:"b",text:"  тараз  "}],correctOptionIds:["a","b"]},{options:[{id:"a",text:"A"},{id:"b",text:"B"}],correctOptionIds:["a"]}]){client({...validQuest},[{...valid,content}]);result=await getOwnedQuestPublicationReadiness(questId);expect(result.status==="ok"&&result.readiness.ready).toBe(false);}});});
